version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - OpenAI__ApiKey=${OPENAI_API_KEY}
      - OpenAI__BaseUrl=${OPENAI_BASE_URL:-}
      - OpenAI__Model=${OPENAI_MODEL:-gpt-4o-realtime-preview-2024-10-01}
      - OpenAI__Voice=${OPENAI_VOICE:-alloy}
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
