services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - OpenAI__ApiKey=${OPENAI_API_KEY}
      - OpenAI__BaseUrl=${OPENAI_BASE_URL}
      - OpenAI__Model=${OPENAI_MODEL}
      - OpenAI__Voice=${OPENAI_VOICE}
      - OpenAI__SystemInstructions=${OPENAI_SYSTEM_INSTRUCTIONS}
    env_file:
      - .env
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
